### ISSUE TITLE
Ejercicio 1: Aclarar a que se refiere con que denote "Azul"

### ISSUE THREAD

**Issue by jesuslombardo** [sagrado-corazon-alcal/mumuki-guia-fundamentos-practica-igualmente-conectados#3]
La gran mayoría de alumnos nos consultan sobre este ejercicio, habría que aclarar que significa que denote Azul, dar un ejemplo más claro para bajarlo un poco. y Luego se entienda que el nroBolitas vaya en cantidad. A su vez aclarar que el nombre de las funciones siempre tiene que ver con el tipo de dato que esperan devolver, Esto puede ayudar en los siguientes ejercicios!

**Comment by faloi** [comment]
De acuerdo, la consigna no es súper clara al respecto, hay que ser aún más explícito. Yo creo que agregar una pista con un ejemplo (digamos, con manzanas o cualquier otra cosa) sería suficiente.

Más allá de eso, me preocupa que el ejercicio no logre transmitir la motivación: dejar de hablar de bolitas y empezar a pensar en elementos del problema (estudiantes, compus, etc.). En general, ¿te hacen preguntas sobre la utilidad del ejercicio o sólo apuntan a cómo resolverlo correctamente?

**Comment by jesuslombardo** [comment]
Mirá, en general este capítulo, es polémico a la cantidad de consultas. Es el más consultado.
Creo que no llegan a entender el para qué?, porque de hecho, no se aprende mucho tipo FOR, IF, y cosas lógicas, sino más que nada sobre Dominio del problema, pero tampoco se llega a entender muy bien.

Yo veo dos opciones, 
1) Ir arreglado artesanalmente los ejercicios, aclarando con ejemplos, y luego buscar de aclarar con más textos.
2) Sacar ejercicios , dejar algunos que describan claramente que se quiere decir con DOMINIO del problema (esto tomaría más tiempo).

Como prefieras ves otras opciones???
Aguardo tu comentario!

**Comment by faloi** [comment]
Lo interesante de esta guía es que te hace integrar todos los conceptos que viste hasta el momento para resolver un problema no trivial, y es bastante menos guiada que las anteriores (a propósito, para que quienes piensan que la tienen clara pero descubran que no es así se vean forzados a preguntar). 

Con eso como horizonte, intentaría no quitarle dificultad sin que eso implique hacer que los ejercicios sean imposibles. Por lo pronto voy a modificar la redacción del primero y seguimos charlando sobre los demás, tratando de diferenciar cuándo las quejas son porque el enunciado no se comprende (como es este caso) y cuándo son porque resulta difícil.
